name: 'Get Owners'
description: 'Parse Owners file and expose approvers, reviewers and random reviewers'
inputs:
  owners-path:  # id of input
    description: 'OWNERS file repo path (including the actual file name)'
    required: false
    default: 'OWNERS'
  n-random-reviewers:
    description: 'Number of random reviewers you want to generate'
    required: false
  auto-add-reviewers:
    description: 'Should add the random reviewers to pr automatically. Ignored if pr not found'
    required: false
    default: false
  token:
    description: 'Secret Token to add Reviewers'
    required: false
outputs:
  approvers:
    description: 'All the approvers in the OWNERS file'
  reviewers:
    description: 'All the reviewers in the OWNERS file'
  random-reviewers:
    description: 'Random reviewers excluding sender'
runs:
  using: 'node16'
  main: 'dist/index.js'