on: push

jobs:
  test_get_owners_action:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Parse OWNERS
        id: owners
        uses: ./
        with:
          owners-path: './test/OWNERS'
          n-random-reviewers: 2
      - name: Get approvers
        run: echo "The Approvers are ${{ steps.owners.outputs.approvers }}"
      - name: Get reviewers
        run: echo "The Reviewers are ${{ steps.owners.outputs.reviewers }}"
      - name: Get random reviewers
        run: echo "The Random reviewers are ${{ steps.owners.outputs.random-reviewers }}"